# Generated by Django 6.1 on 2026-08-24 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, default='', max_length=150)),
                ('industry', models.CharField(blank=True, default='Technology', max_length=100)),
                ('company_size', models.CharField(choices=[('1', 'Individual / 1 person'), ('2-10', 'Small (2-10 employees)'), ('11-50', 'Medium (11-50 employees)'), ('51-200', 'Mid-Large (51-200 employees)'), ('200+', 'Enterprise (200+ employees)')], default='2-10', max_length=20)),
                ('company_website', models.URLField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('about_company', models.TextField(blank=True, default='')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('hire_count', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
