# Generated by Django 6.1 on 2026-08-24 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Development', 'Software & Web Development'), ('AI & Data', 'AI, ML & Data Science'), ('Design', 'Design & Creative'), ('Mobile', 'Mobile App Development'), ('DevOps', 'DevOps & Cloud'), ('Marketing', 'Marketing & Writing'), ('Other', 'Other')], default='Development', max_length=50)),
                ('icon', models.CharField(blank=True, default='bi-code-slash', max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FreelancerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Professional Freelancer', max_length=150)),
                ('bio', models.TextField(blank=True, default='')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=35.0, max_digits=10)),
                ('availability', models.CharField(choices=[('available', 'Available for Work'), ('busy', 'Partially Available'), ('not_available', 'Not Available')], default='available', max_length=20)),
                ('experience_level', models.CharField(choices=[('entry', 'Entry Level (1-2 yrs)'), ('intermediate', 'Intermediate (3-5 yrs)'), ('expert', 'Expert (5+ yrs)')], default='intermediate', max_length=20)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('total_reviews_count', models.PositiveIntegerField(default=0)),
                ('completed_projects_count', models.PositiveIntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='freelancers.freelancerprofile')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('project_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='freelancers.freelancerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FreelancerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='advanced', max_length=20)),
                ('years_of_experience', models.PositiveIntegerField(default=2)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_skills', to='freelancers.freelancerprofile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_freelancers', to='freelancers.skill')),
            ],
            options={
                'unique_together': {('freelancer', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='freelancers', through='freelancers.FreelancerSkill', to='freelancers.skill'),
        ),
    ]
