# Generated by Django 6.1 on 2026-08-24 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='category',
            field=models.CharField(default='Web Application', max_length=50),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='github_url',
            field=models.URLField(blank=True, default='', help_text='GitHub repository URL'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='tags',
            field=models.CharField(blank=True, default='', help_text='e.g. Django, React, Google Gemini API', max_length=255),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_projects', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='project_url',
            field=models.URLField(blank=True, default='', help_text='Live demo or website URL'),
        ),
    ]
