# Generated by Django 6.1 on 2026-08-24 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0002_portfolioitem_category_portfolioitem_github_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/slides/')),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='freelancers.portfolioitem')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
